Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "django-piscine"

  # Project shared between host and guest
  config.vm.synced_folder "../Django_0_Initiation",
                          "/home/vagrant/Django_0_Initiation"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "django-piscine"

    vb.gui = true
    vb.memory = 4096
    vb.cpus = 2

    # Host <-> Guest clipboard
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    vb.customize ["modifyvm", :id, "--drag-and-drop", "bidirectional"]
  end

  config.vm.provision "shell", path: "setup.sh"

end